src/java/com/mingle/pbe/beans/Agent.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mingle.pbe.beans;

import com.mingle.pbe.AgentState;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author chris.weaver
 */
public class Agent
{
    private int id, numTemplates, currPos;
    private AgentState state;
    private Date startTm;
    private Date lastCheck;
    private Book book;
    private boolean isExit = false;
    
    public Agent() {}
    
    public Agent(int id)
    {
        this.id = id;
        this.state = AgentState.Idle;
    }
    
    public void interrupt()
    {
        isExit = true;
    }    
    
    public boolean isExit()
    {
        return isExit;
    }
    
    public void pause() {
        state = AgentState.Paused;
    }
    
    public void resume() {
        state = AgentState.Idle;
    }
    
    public void kill() {
        state = AgentState.Interrupt;
    }
    
    /**
     * @return the rowId
     */
    public int getId() {
        return id;
    }

    /**
     * @param rowId the rowId to set
     */
    public void setId(int id) {
        this.id = id;;
    }

    @Override
    public boolean equals(Object obj)
    {
        Agent other = (Agent) obj;
        
        if(this.id == other.id)
            return true;
        else
            return false;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 89 * hash + String.valueOf(this.id).hashCode();
        return hash;
    }

    /**
     * @return the status
     */
    public AgentState getState() {
        return state;
    }

    public String getPID() {
        return (book != null) ? String.valueOf(book.getPID()) : "";
    }
    
    public String getCustNo() {
        return (book != null) ? book.getCustno() : "";
    }
    
    public String getBookName() {
        return (book != null) ? book.getBookName() : "";
    }
    
    public void start(Book book) {
        this.startTm = Calendar.getInstance().getTime();
        this.book = book;
        this.state = AgentState.Running;
    }
    
    public void finish()
    {
        this.book = null;
        this.startTm = null;
        this.state = AgentState.Idle;
    }
    
    /**
     * @return the startTm
     */
    public Date getStartTm() {
        return startTm;
    }

    /**
     * @return the lastCheck
     */
    public Date getLastCheck() {
        return lastCheck;
    }

    /**
     * @param lastCheck the lastCheck to set
     */
    public void setLastCheck(Date lastCheck) {
        this.lastCheck = lastCheck;
    }

    /**
     * @return the numTemplates
     */
    public int getNumTemplates() {
        return numTemplates;
    }

    /**
     * @param numTemplates the numTemplates to set
     */
    public void setNumTemplates(int numTemplates) {
        this.numTemplates = numTemplates;
    }

    /**
     * @return the currTemplate
     */
    public int getCurrPos() {
        return currPos;
    }

    /**
     * @param currTemplate the currTemplate to set
     */
    public void setCurrPos(int currPos) {
        this.currPos = currPos;
    }
}

web/WEB-INF/jsp/index.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<!DOCTYPE HTML>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="refresh" content="5">
        <title>PBEngine Console</title>
    </head>

    <body>
        <h2>PBEngine Status</h2>
        Current Time: ${msg}<br/><br/>
        <table border="1">
            <tr>
                <td width="75" style="text-align: center;">Agent Id</td>
                <td width="80" style="text-align: center;">State</td>
                <td width="125" style="text-align: center;">Last Check In</td>
                <td width="75" style="text-align: center;">PID</td>
                <td width="100">Customer #</td>
                <td width="200">Book Name</td>
                <td width="75" style="text-align: center;">Completed</td>
                <td width="200">Start Time</td>
            </tr>
            <c:forEach var="agent" items="${agents}">
            <tr>
                <td style="text-align: center;">${agent.id}</td>
                <td style="text-align: center;">
                    <c:choose>
                        <c:when test="${agent.state == 'Paused'}">
                            <a href='pause.htm?agent_id=<c:out value="${agent.id}"/>'>${agent.state}</a>
                        </c:when>
                        <c:when test="${agent.state == 'Running'}">
                            ${agent.state}
                        </c:when>
                        <c:otherwise>
                            <a href='pause.htm?agent_id=<c:out value="${agent.id}"/>'>${agent.state}</a>
                        </c:otherwise>
                    </c:choose>                    
                </td>
                <td style="text-align: center;">
                    <fmt:formatDate pattern="HH:mm:ss.SSSS" value="${agent.lastCheck}" />
                </td>
                <td style="text-align: center;">${agent.PID}</td>
                <td>${agent.custNo}</td>
                <td>${agent.bookName}</td>
                <td style="text-align: center;">
                    <c:if test="${agent.PID != ''}">
                        <fmt:formatNumber value="${(agent.currPos / agent.numTemplates) * 100}" maxFractionDigits="0" /> %
                    </c:if>
                </td>
                <td><fmt:formatDate type="both" value="${agent.startTm}" /></td>
            </tr>
            </c:forEach>
        </table>  
        
        <h3>In Queue</h3>
        <table border="1">
            <tr>
                <td width="100">Customer #</td>
                <td width="200">Book Name</td>
                <td width="250">Queued Time</td>
            </tr>
            <c:forEach var="book" items="${queuedBooks}">
            <tr>
                <td width="100">${book.custno}</td>
                <td width="200">${book.bookName}</td>
                <td width="250"><fmt:formatDate type="both" value="${book.queueTime}" /></td>
            </tr>
            </c:forEach>
        </table> 
        
    </body>
</html>

web/WEB-INF/jsp/rawText.jsp
<%@ taglib uri='http://java.sun.com/jsp/jstl/core' prefix='c'%>
<c:out value="${content}" escapeXml="false" />